"""crear esquema inicial

Revision ID: db5a336076ca
Revises:
Create Date: 2025-11-16 18:16:48.334295

"""

from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db5a336076ca"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paciente",
        sa.Column("id_paciente", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sexo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("edad", sa.Integer(), nullable=False),
        sa.Column("zona_residencia", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_dx", sa.Date(), nullable=False),
        sa.Column("tipo_cancer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("estadio", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("aseguradora", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("adherencia_12m", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id_paciente"),
    )
    op.create_table(
        "consulta",
        sa.Column("id_consulta", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fecha_consulta", sa.Date(), nullable=False),
        sa.Column("motivo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prioridad", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("especialista", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id_paciente", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_paciente"],
            ["paciente.id_paciente"],
        ),
        sa.PrimaryKeyConstraint("id_consulta"),
    )
    op.create_table(
        "laboratorio",
        sa.Column("id_lab", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fecha_muestra", sa.Date(), nullable=False),
        sa.Column("tipo_prueba", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resultado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resultado_numerico", sa.Float(), nullable=True),
        sa.Column("unidad", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id_paciente", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_paciente"],
            ["paciente.id_paciente"],
        ),
        sa.PrimaryKeyConstraint("id_lab"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("laboratorio")
    op.drop_table("consulta")
    op.drop_table("paciente")
    # ### end Alembic commands ###
